#!/hint/bash

thisdir=$(pwd)

if [[ ! -d $thisdir/meta-newbs ]]; then
    echo "meta-newbs not found!"
    echo "please source this script from the NEWBS root"
    return 1
fi
NEWBSROOT=$(readlink -f $thisdir)
unset thisdir

while (($#)); do
    case "$1" in
        64)
            MACHINE=raspberrypi3-64
            ;;
        build-*)
            BUILD_DIR="$1"
            ;;
        mce)
            DISTRO="newbs-mce"
            ;;
        unifi)
            DISTRO="newbs-unifi"
            ;;
        *)
            echo "Warning: unknown build option '$1'"
            ;;
    esac
    shift
done

# defaults, if not set above
: ${DISTRO:=newbs}
: ${MACHINE:=raspberrypi3-64}
: ${BUILD_DIR:=build-${MACHINE}}

echo "Using MACHINE $MACHINE"
echo "Using BUILD_DIR $BUILD_DIR"

source meta-wild-common/common-envsetup
_wild_yocto_apply_patches
_wild_yocto_symlink_cache_dir downloads
_wild_yocto_symlink_cache_dir sstate-cache

_wild_yocto_python3_hack pre
export TEMPLATECONF="$NEWBSROOT/meta-newbs/conf"
echo $TEMPLATECONF
source openembedded-core/oe-init-build-env $BUILD_DIR
unset TEMPLATECONF
_wild_yocto_python3_hack post

# now we're in the build directory and should have bblayers.conf and local.conf
BB_CONF="conf/bblayers.conf"
LOCAL_CONF="conf/local.conf"

# post-process conf files
_wild_yocto_subst_confvars $BB_CONF $LOCAL_CONF -- NEWBSROOT MACHINE DISTRO

# remove meta-kodi unless we're using the mce distro
if [[ $DISTRO != "newbs-mce" ]]; then
    sed -i 's/^BBLAYERS.*meta-kodi.*/#\0/' $BB_CONF
fi

# unset unused variables
unset BB_CONF LOCAL_CONF NEWBSROOT MACHINE DISTRO
_wild_yocto_unset_functions
